import type React from 'react'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    [name: string]: THREE.Mesh | THREE.Group
  }
  materials: {
    [name: string]: THREE.Material
  }
}

interface AngklungProps {
  activeNotes: Set<string>;
}

export function AngklungModel({ activeNotes, ...props }: AngklungProps & React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/angklung.glb') as unknown as GLTFResult;

  useFrame((state) => {
    // Definisi nama-nama angklung yang valid
    const targetNodes = [
      'G-Object009', 'G-Object018', 'G-Object001', 'G-Object002', 
      'G-Object003', 'G-Object004', 'G-Object005', 'G-Object006', 
      'G-Object007', 'G-Object008', 'G-Object010', 'G-Object011', 
      'G-Object013', 'G-Object012'
    ];

    targetNodes.forEach((nodeName) => {
      const node = nodes[nodeName];
      if (node) {
        if (activeNotes.has(nodeName)) {
          // Animasi goyang (goyang di sumbu Z/X tergantung orientasi aslinya)
          // Menggunakan Math.sin untuk getaran cepat (speed: 30)
          node.rotation.x = Math.sin(state.clock.elapsedTime * 30) * 0.15;
        } else {
          // Kembali ke posisi diam secara perlahan (Lerp)
          node.rotation.x = THREE.MathUtils.lerp(node.rotation.x, 0, 0.2);
        }
      }
    });
  });

  return (
    <group {...props} dispose={null}>
      {/* Rangka Bambu */}
      <mesh geometry={(nodes.Cube as THREE.Mesh).geometry} material={materials['Material.018']} position={[0, 0.556, 0.475]} scale={[0.015, 0.018, 0.025]} />
      <mesh geometry={(nodes.Cube001 as THREE.Mesh).geometry} material={materials['Material.018']} position={[0, 1.239, 0.475]} rotation={[-0.209, 0, 0]} scale={[0.011, 0.025, 0.025]} />
      <mesh geometry={(nodes.Cube003 as THREE.Mesh).geometry} material={materials['Material.018']} position={[0.304, 0.641, 0.484]} rotation={[0, 0.052, Math.PI / 2]} scale={[0.016, 0.026, 0.026]} />
      <mesh geometry={(nodes.Cylinder as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, -0.298]} scale={0.038} />
      <mesh geometry={(nodes.Cylinder001 as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, 1.2]} scale={0.038} />
      <mesh geometry={(nodes.Cylinder002 as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, -0.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.044, 0.021, 0.044]} />
      <mesh geometry={(nodes.Cylinder003 as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, 1.2]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.044, 0.025, 0.044]} />
      
      {/* 14 Angklung Grup */}
      <primitive object={nodes['G-Object009']} />
      <primitive object={nodes['G-Object018']} />
      <primitive object={nodes['G-Object001']} />
      <primitive object={nodes['G-Object002']} />
      <primitive object={nodes['G-Object003']} />
      <primitive object={nodes['G-Object004']} />
      <primitive object={nodes['G-Object005']} />
      <primitive object={nodes['G-Object006']} />
      <primitive object={nodes['G-Object007']} />
      <primitive object={nodes['G-Object008']} />
      <primitive object={nodes['G-Object010']} />
      <primitive object={nodes['G-Object011']} />
      <primitive object={nodes['G-Object013']} />
      <primitive object={nodes['G-Object012']} />
    </group>
  )
}

useGLTF.preload('/models/angklung.glb')
