/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import type React from 'react'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import angklungModelUrl from '~/assets/models/angklung.glb'

type GLTFResult = GLTF & {
  nodes: {
    [name: string]: THREE.Mesh | THREE.Group
  }
  materials: {
    [name: string]: THREE.Material
  }
}

interface AngklungProps {
  activeNotes: Set<string>;
}

export function AngklungModel({ activeNotes, ...props }: AngklungProps & React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(angklungModelUrl) as unknown as GLTFResult;
  
  // Referensi untuk menyimpan grup pembungkus (Pivot Wrapper)
  const pivotWrappers = useRef<Record<string, THREE.Group>>({});

  useEffect(() => {
    const targetNodes = [
      'G-Object009', 'G-Object018', 'G-Object001', 'G-Object002',
      'G-Object003', 'G-Object004', 'G-Object005', 'G-Object006',
      'G-Object007', 'G-Object008', 'G-Object010', 'G-Object011',
      'G-Object013', 'G-Object012'
    ];

    const pivotOffsetY = 0.5;
    const originalParents: Record<string, THREE.Object3D> = {};
    const originalPositions: Record<string, THREE.Vector3> = {};

    targetNodes.forEach((nodeName) => {
      const node = nodes[nodeName];
      if (node && !pivotWrappers.current[nodeName]) {
        const wrapper = new THREE.Group();

        originalParents[nodeName] = node.parent!;
        originalPositions[nodeName] = node.position.clone();

        wrapper.position.copy(node.position);
        wrapper.position.y += pivotOffsetY;

        const parent = node.parent;
        if (parent) {
          parent.remove(node);
          parent.add(wrapper);
        }

        wrapper.add(node);
        node.position.set(0, -pivotOffsetY, 0);
        pivotWrappers.current[nodeName] = wrapper;
      }
    });

    return () => {
      // kembalikan node ke parent & posisi asli agar mount berikutnya bersih
      targetNodes.forEach((nodeName) => {
        const wrapper = pivotWrappers.current[nodeName];
        const node = nodes[nodeName];
        const origParent = originalParents[nodeName];
        const origPos = originalPositions[nodeName];
        if (wrapper && node && origParent && origPos) {
          wrapper.remove(node);
          origParent.remove(wrapper);
          origParent.add(node);
          node.position.copy(origPos);
        }
      });
      pivotWrappers.current = {};
    };
  }, [nodes]);

  useFrame((state) => {
    const targetNodes = [
      'G-Object009', 'G-Object018', 'G-Object001', 'G-Object002', 
      'G-Object003', 'G-Object004', 'G-Object005', 'G-Object006', 
      'G-Object007', 'G-Object008', 'G-Object010', 'G-Object011', 
      'G-Object013', 'G-Object012'
    ];

    targetNodes.forEach((nodeName) => {
      // Yang kita putar sekarang adalah WRAPPER-nya (titik tumpu yang ada di atas)
      const wrapper = pivotWrappers.current[nodeName];

      if (wrapper) {
        if (activeNotes.has(nodeName)) {
          // Animasi mengayun
          wrapper.rotation.z = Math.sin(state.clock.elapsedTime * 30) * 0.13;
        } else {
          // Berhenti perlahan
          wrapper.rotation.z = THREE.MathUtils.lerp(wrapper.rotation.z, 0, 0.2);
        }
      }
    });
  });

  return (
    <group {...props} dispose={null}>
      {/* Rangka Bambu */}
      <mesh geometry={(nodes.Cube as THREE.Mesh).geometry} material={materials['Material.018']} position={[0, 0.556, 0.475]} scale={[0.015, 0.018, 0.025]} />
      <mesh geometry={(nodes.Cube001 as THREE.Mesh).geometry} material={materials['Material.018']} position={[0, 1.239, 0.475]} rotation={[-0.209, 0, 0]} scale={[0.011, 0.025, 0.025]} />
      <mesh geometry={(nodes.Cube003 as THREE.Mesh).geometry} material={materials['Material.018']} position={[0.304, 0.641, 0.484]} rotation={[0, 0.052, Math.PI / 2]} scale={[0.016, 0.026, 0.026]} />
      <mesh geometry={(nodes.Cylinder as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, -0.298]} scale={0.038} />
      <mesh geometry={(nodes.Cylinder001 as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, 1.2]} scale={0.038} />
      <mesh geometry={(nodes.Cylinder002 as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, -0.298]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.044, 0.021, 0.044]} />
      <mesh geometry={(nodes.Cylinder003 as THREE.Mesh).geometry} material={materials.Bamboo} position={[0, 0.495, 1.2]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.044, 0.025, 0.044]} />
      
      {/* 14 Angklung Grup */}
      <primitive object={nodes['G-Object009']} />
      <primitive object={nodes['G-Object018']} />
      <primitive object={nodes['G-Object001']} />
      <primitive object={nodes['G-Object002']} />
      <primitive object={nodes['G-Object003']} />
      <primitive object={nodes['G-Object004']} />
      <primitive object={nodes['G-Object005']} />
      <primitive object={nodes['G-Object006']} />
      <primitive object={nodes['G-Object007']} />
      <primitive object={nodes['G-Object008']} />
      <primitive object={nodes['G-Object010']} />
      <primitive object={nodes['G-Object011']} />
      <primitive object={nodes['G-Object013']} />
      <primitive object={nodes['G-Object012']} />
    </group>
  )
}

useGLTF.preload(angklungModelUrl)
